### ISSUE TITLE
Freebase can return multiple content ratings for an item

### ISSUE THREAD

**Issue by chriscurtis** [plexinc-agents/PlexMovie.bundle#7]
In some cases, Freebase can return multiple content ratings for an item. Since they're apparently returned in a semi-random order, that can affect which rating is used for the item.

Example (The Dark Knight): http://www.freebase.com/m/0btpm6
Freebase lists both PG-13 and G ratings

In testing, the G rating was picked up for me (as well as a forum user who reported this).

**Comment by maxGreenblatt** [comment]
OTA fixes this - Ratings are now by country based on a user pref
