### ISSUE TITLE
allow overriding of movie title by other agents / fix international movie titles

### ISSUE THREAD

**Issue by OttoKerner** [plexinc-agents/PlexMovie.bundle#9]
this is referring to
https://github.com/plexinc-agents/TheMovieDB.bundle/issues/32

As analysis carried out in that above linked GHI shows, the Freebase agent doesn't allow overriding of movie title by other agents.
But this is necessary, because Freebase itself has a bug which prevents localized/translated movie titles.

Changing to TheMoviedatabase agent is not an option because:
There is a rather good metadata database for german movie info (OFDB.de). It also provides the german age classification for movies. 
The metadata agent for OFDB.de only works with the Plex Freebase agent.
Same goes for agents for automatic subtitle downloading.

So if a german user wants german movie titles and german age classification for use with the Plex Home feature (and maybe automatic subs), he is totally out of luck.
And I presume the translated movie title flaw of Freebase affects not only german users.

So the following metadata agent configuration doesn't give translated movie titles, even though both OFDB.de and TheMovieDatabase could supply them:
![localized_titles_fail](https://cloud.githubusercontent.com/assets/10280992/7903303/b3bacf56-07d7-11e5-808f-940bcf1d1a0e.png)

**Comment by mmccurdy07** [comment]
Fixed in https://github.com/plexinc-agents/LocalMedia.bundle/commit/36f47a07599483035a6e649a0c00f6e3c0eb1934.

**Comment by OttoKerner** [comment]
confirmed fixed. now working as it should. Thank you!
